[workspace]
channels = ["conda-forge"]
name = "SatArgoBbp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.4.5,<5"
ipython = ">=9.4.0,<10"
pandas = ">=2.3.1,<3"
scikit-learn = ">=1.7.1,<2"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"

